import Head from "next/head";
import Generator from "./Generator/Generator";
import { AlertPopUp } from "./components/AlertPopUp/AlertPopUp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gerador de senhas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            body {
              margin: 0;
            }
          `}
        </style>
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
          backgroundColor: "#121214",
          gap: "2rem",
        }}
      >
        <Generator />
        <AlertPopUp />
      </main>
    </>
  );
}
